#!/bin/bash

# see if global variable is set
# LSeismicUnix is a global variable for locating the  main folder

 if [ -z "${PL_LOCAL}" ]; then

 	echo "global variable LSUcpan_main must be set"
 	echo "e.g. in .bashrc: "
 	echo " export LSeismicUnix=/usr/local/pl "
 	
 else
	perl $LSeismicUnix/main/L_SU_project_selector.pl
	perl $LSeismicUnix/main/L_SUV0.6.6.pl
 fi
