#!/bin/sh

# see if global variable is set
# global variable SeismicUnixGui_script locates main folder

 if [ -z "${SeismicUnixGui_script}" ]; then

 	echo "global variable SeismicUnixGui_script must be set"
 	echo "e.g. in .bashrc: "
 	echo " export SeismicUnixGui_script=/Location/of/script/folder "

 else

	# run Sudipfilt
	perl $SeismicUnixGui_script/Sudipfilt.pl
fi
