#! /bin/sh
#  usage: mod user sampling_interval(in microsecs)
# ss is the ascii filename
#  plotdat.sh plots a default filename 
set -x
out_path=.
#
#
# x    kills active PID's for suximage and suxgraph
#  set up for ricker wavelet
sampling_interval=$1 # microsecs
./synseis.sh >$out_path/ss
plot_zvreg.sh 
plot_zrhoreg.sh 
plot_rc.sh
plot_ss.sh $sampling_interval
# clean.sh ./
