#!/bin/bash

# see if global variable is set
# L_SU is a global variable for locating the  main folder

 if [ -z "${SeismicUnixGui}" ]; then

 	echo "global variable L_SU must be set"
 	echo "e.g. in .bashrc: "
 	echo " export SeismicUnixGui=/usr/local/pl/SeismicUnixGui "

 else

	perl $L_SU/L_su_plot.pl

 fi
