#! /bin/sh
set -x
 
#
# This script produces a velocity model for the modelling
#
# To view the model type:
#  ximage < velocity.bin n1=100
#
#
# Stig-Kyrre Foss, 29.Oct 2001

ninf=1 nx=100 nz=100
dx=5 dz=5
fx=0.0 fz=0.0
v00=750.,1000.
dvdx=0.0
npmax=100
dvdz=0.0,0.0
boundaries=boundaries.txt

DIR_BIN=/home/gllore/demos/seismics/data/Synthetic/Finite_Difference/Sufctanismod/Xdemo1/1/bin/gllore
DIR_BIN=.
DIR_TXT=/home/gllore/demos/seismics/data/Synthetic/Finite_Difference/Sufctanismod/Xdemo1/1/txt/gllore
#DIR_TXT=.

unif2 <  $DIR_TXT/$boundaries > $DIR_BIN/vpsmtest.bin nx=$nx nz=$nz ninf=$ninf dx=$dx dz=$dz\
     dvdx=$dvdx v00=$v00 dvdz=$dvdz npmax=$npmax
     
v00=300.,500.

    
unif2 <  $DIR_TXT/$boundaries > $DIR_BIN/vssmtest.bin nx=$nx nz=$nz ninf=$ninf dx=$dx dz=$dz\
     dvdx=$dvdx v00=$v00 dvdz=$dvdz npmax=$npmax 

v00=1000.,1100.

unif2 <  $DIR_TXT/$boundaries > $DIR_BIN/rhosmtest.bin nx=$nx nz=$nz ninf=$ninf dx=$dx dz=$dz\
     dvdx=$dvdx v00=$v00 dvdz=$dvdz npmax=$npmax

v00=0.,0.

unif2 <  $DIR_TXT/$boundaries > $DIR_BIN/deltasmtest.bin nx=$nx nz=$nz ninf=$ninf dx=$dx dz=$dz\
     dvdx=$dvdx v00=$v00 npmax=$npmax

v00=0.,0.

unif2 <  $DIR_TXT/$boundaries > $DIR_BIN/epsilonsmtest.bin nx=$nx nz=$nz ninf=$ninf dx=$dx dz=$dz\
     dvdx=$dvdx v00=$v00 npmax=$npmax 

cp $DIR_BIN/epsilonsmtest.bin $DIR_BIN/dummy_zero.bin

#   Transform into stiffness coefficients
vpfile=$DIR_BIN/vpsmtest.bin
vpfile=$DIR_BIN/vpsmtest.bin
vsfile=$DIR_BIN/vssmtest.bin
rhofile=$DIR_BIN/rhosmtest.bin
epsfile=$DIR_BIN/epsilonsmtest.bin
deltafile=$DIR_BIN/deltasmtest.bin
gammafile=$DIR_BIN/gamma_lens
c11_file=$DIR_BIN/c11smtest.bin
c13_file=$DIR_BIN/c13smtest.bin
c33_file=$DIR_BIN/c33smtest.bin
c44_file=$DIR_BIN/c44smtest.bin 
c66_file=$DIR_BIN/c66smtest.bin


#vel2stiff  vsfile=$vsfile rhofile=$rhofile epsfile=$epsfile vpfile=$vpfile \
vel2stiff \
c11_file=$c11_file c13_file=$c13_file c33_file=$c33_file \
deltafile=$deltafile nx=$nx nz=$nz \
c44_file=$c44_file c66_file=$c66_file \
vpfile=$vpfile vsfile=$vsfile rhofile=$rhofile epsfile=$epsfile 

exit 0    




