#!/bin/bash

# see if global variable is set
# LSeismicUnix_script is a global variable for locating the script folder

 if [ -z "${LSeismicUnix_script}" ]; then

 	echo "global variable LSeismicUnix_script must be set"
 	echo "e.g. in .bashrc: "
 	echo " export LSeismicUnix_script=/Location/of/script/folder "
 	
 else
	perl $LSeismicUnix_script/L_SU_project_selector.pl
	perl $LSeismicUnix_script/L_SUV0.6.6.pl
 fi
