#!/bin/sh

# see if global variable is set
# global variable LSeismicUnix_script locates main folder

 if [ -z "${LSeismicUnix_script}" ]; then

 	echo "global variable LSeismicUnix_script must be set"
 	echo "e.g. in .bashrc: "
 	echo " export LSeismicUnix_script=/Location/of/script/folder "

 else

	# run Sudipfilt
	perl $LSeismicUnix_script/Sudipfilt.pl
fi
