#!/bin/sh

# see if global variable is set
# global variable LSeismicUnix locates main folder

 if [ -z "${PL_LOCAL}" ]; then

 	echo "global variable PL_LOCAL must first be set"
 	echo "e.g. in .bashrc: "
 	echo " export PL_LOCAL=/usr/local/pl "

 else

	# run iBottomMute.pl
	# echo "perl" $PL_LOCAL/"LSeismicUnix/big_streams/iBottom_Mute.pl"
	perl $PL_LOCAL/LSeismicUnix/big_streams/iBottomMute.pl
fi
