#!/bin/sh

# see if global variable is set
# global variable PL_LOCAL locates main folder

 if [ -z "${PL_LOCAL}" ]; then

 	echo "global variable PL_LOCAL must first be set"
 	echo "e.g. in .bashrc: "
 	echo " export PL_LOCAL=/usr/local/pl "

 else

	# run Sseg2su.pl
	# echo "perl" $PL_LOCAL/LSeismicUnix/big_streams/Sseg2su.pl"
	perl $LSeismicUnix/big_streams/Sseg2su.pl
fi
