#!/bin/sh

# see if global variable is set
# global variable L_SU locates main folder

 if [ -z "${L_SU}" ]; then

 	echo "global variable L_SU must be set"
 	echo "e.g. in .bashrc: "
 	echo " export L_SU=/usr/local/pl "

 else

	# run Sudipfilt
	perl $L_SU/big_streams/Sudipfilt.pl
fi
