#!/bin/sh

# see if global variable is set
# global variable PL_LOCAL locates main folder

 if [ -z "${PL_LOCAL}" ]; then

 	echo "global variable PL_LOCAL must first be set"
 	echo "e.g. in .bashrc: "
 	echo " export PL_LOCAL=/usr/local/pl/ "

 else

	# run Synseis
	# echo "perl" $PL_LOCAL"/LSeismicUnix/big_streams/Synseis.pl"
	perl $PL_LOCAL/LSeismicUnix/big_streams/Synseis.pl
fi
